site_name: alt:V Python Module

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt

docs_dir: articles
repo_name: Marvisak/altv-python-module
repo_url: https://github.com/Marvisak/altv-python-module
edit_uri: edit/dev/docs/articles

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/objects.inv
            - https://mkdocstrings.github.io/griffe/objects.inv
          rendering:
            show_if_no_docstring: True
            show_source: False
            show_signature_annotations: True
            merge_init_into_class: True
            members_order: source

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite


nav:
  - Home: "index.md"
  - Intro: "intro.md"
  - Events: "events.md"
  - Tasks and Timers: "tasks.md"
  - Vectors: "vectors.md"
  - Vehicle: "vehicle.md"
  - ColShapes: "colshapes.md"
  - Additional Information: "additional-information.md"
  - API Reference:
      Events: "api-reference/events.md"
      API: "api-reference/api.md"
