name: Build & Deploy
on:
  workflow_dispatch:
  push:
    tags:
      - "dev/*.*-dev*"
      - "rc/*.*-rc*"
      - "release/*.*"

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false

  build-windows:
    name: Build Windows server module
    runs-on: windows-2019
    needs: [create-release]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Build
        shell: cmd
        run: build.bat

      - name: Zip artifacts
        run: |
          cd dist
          tar -acf ..\python-module-windows.zip *

      - name: Upload artifacts to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: python-module-windows.zip
          asset_name: python-module-windows.zip
          asset_content_type: application/octet-stream

  build-linux:
    name: Build Linux server module
    runs-on: ubuntu-20.04
    needs: [create-release]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Build
        run: |
          sudo chmod +x build.sh
          ./build.sh
      - name: Zip artifacts
        run: |
          cd dist
          zip -r ../python-module-linux .
      - name: Upload artifacts to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: python-module-linux.zip
          asset_name: python-module-linux.zip
          asset_content_type: application/octet-stream
